# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import scarphase_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='dejavu.proto',
  package='dejavu.proto',
  serialized_pb='\n\x0c\x64\x65javu.proto\x12\x0c\x64\x65javu.proto\x1a\x0fscarphase.proto\"\xc4\x01\n\x06\x41\x63\x63\x65ss\x12\n\n\x02pc\x18\x01 \x02(\x04\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\x04\x12\x0c\n\x04time\x18\x03 \x02(\x04\x12\x13\n\x0bglobal_time\x18\x04 \x02(\x04\x12\'\n\x04type\x18\x05 \x02(\x0e\x32\x19.dejavu.proto.Access.Type\x12\x0b\n\x03tid\x18\x06 \x02(\x04\x12\x0b\n\x03wid\x18\x07 \x01(\x04\"7\n\x04Type\x12\n\n\x06UNKOWN\x10\x00\x12\x08\n\x04READ\x10\x01\x12\t\n\x05WRITE\x10\x02\x12\x0e\n\nREAD_WRITE\x10\x03\"G\n\x06Sample\x12$\n\x06\x61\x63\x63\x65ss\x18\x01 \x03(\x0b\x32\x14.dejavu.proto.Access\x12\x17\n\x0fline_size_bytes\x18\x02 \x01(\r\"\x95\x01\n\x06Header\x12\x0c\n\x04name\x18\x01 \x01(\t\x12-\n\x07setting\x18\x02 \x03(\x0b\x32\x1c.dejavu.proto.Header.Setting\x1a\'\n\x07Version\x12\r\n\x05major\x18\x01 \x02(\x05\x12\r\n\x05minor\x18\x02 \x02(\x05\x1a%\n\x07Setting\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"~\n\x07Profile\x12$\n\x06header\x18\x01 \x02(\x0b\x32\x14.dejavu.proto.Header\x12$\n\x06sample\x18\x02 \x03(\x0b\x32\x14.dejavu.proto.Sample\x12\'\n\x06window\x18\x03 \x03(\x0b\x32\x17.scarphase.proto.Window')



_ACCESS_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='dejavu.proto.Access.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='UNKOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='READ', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WRITE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='READ_WRITE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=189,
  serialized_end=244,
)


_ACCESS = descriptor.Descriptor(
  name='Access',
  full_name='dejavu.proto.Access',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pc', full_name='dejavu.proto.Access.pc', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='dejavu.proto.Access.address', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time', full_name='dejavu.proto.Access.time', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='global_time', full_name='dejavu.proto.Access.global_time', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='dejavu.proto.Access.type', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tid', full_name='dejavu.proto.Access.tid', index=5,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wid', full_name='dejavu.proto.Access.wid', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACCESS_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=244,
)


_SAMPLE = descriptor.Descriptor(
  name='Sample',
  full_name='dejavu.proto.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='access', full_name='dejavu.proto.Sample.access', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='line_size_bytes', full_name='dejavu.proto.Sample.line_size_bytes', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=246,
  serialized_end=317,
)


_HEADER_VERSION = descriptor.Descriptor(
  name='Version',
  full_name='dejavu.proto.Header.Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='major', full_name='dejavu.proto.Header.Version.major', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='minor', full_name='dejavu.proto.Header.Version.minor', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=391,
  serialized_end=430,
)

_HEADER_SETTING = descriptor.Descriptor(
  name='Setting',
  full_name='dejavu.proto.Header.Setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='dejavu.proto.Header.Setting.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='dejavu.proto.Header.Setting.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=432,
  serialized_end=469,
)

_HEADER = descriptor.Descriptor(
  name='Header',
  full_name='dejavu.proto.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='dejavu.proto.Header.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='setting', full_name='dejavu.proto.Header.setting', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_HEADER_VERSION, _HEADER_SETTING, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=320,
  serialized_end=469,
)


_PROFILE = descriptor.Descriptor(
  name='Profile',
  full_name='dejavu.proto.Profile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='dejavu.proto.Profile.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sample', full_name='dejavu.proto.Profile.sample', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='window', full_name='dejavu.proto.Profile.window', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=471,
  serialized_end=597,
)

_ACCESS.fields_by_name['type'].enum_type = _ACCESS_TYPE
_ACCESS_TYPE.containing_type = _ACCESS;
_SAMPLE.fields_by_name['access'].message_type = _ACCESS
_HEADER_VERSION.containing_type = _HEADER;
_HEADER_SETTING.containing_type = _HEADER;
_HEADER.fields_by_name['setting'].message_type = _HEADER_SETTING
_PROFILE.fields_by_name['header'].message_type = _HEADER
_PROFILE.fields_by_name['sample'].message_type = _SAMPLE
_PROFILE.fields_by_name['window'].message_type = scarphase_pb2._WINDOW
DESCRIPTOR.message_types_by_name['Access'] = _ACCESS
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Profile'] = _PROFILE

class Access(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCESS
  
  # @@protoc_insertion_point(class_scope:dejavu.proto.Access)

class Sample(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAMPLE
  
  # @@protoc_insertion_point(class_scope:dejavu.proto.Sample)

class Header(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Version(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _HEADER_VERSION
    
    # @@protoc_insertion_point(class_scope:dejavu.proto.Header.Version)
  
  class Setting(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _HEADER_SETTING
    
    # @@protoc_insertion_point(class_scope:dejavu.proto.Header.Setting)
  DESCRIPTOR = _HEADER
  
  # @@protoc_insertion_point(class_scope:dejavu.proto.Header)

class Profile(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROFILE
  
  # @@protoc_insertion_point(class_scope:dejavu.proto.Profile)

# @@protoc_insertion_point(module_scope)
