# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='pincode.proto',
  package='pincode.proto',
  serialized_pb='\n\rpincode.proto\x12\rpincode.proto\"\xb0\x01\n\x06\x41\x63\x63\x65ss\x12\n\n\x02pc\x18\x01 \x02(\x04\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\x04\x12\x0c\n\x04time\x18\x03 \x02(\x04\x12(\n\x04type\x18\x04 \x02(\x0e\x32\x1a.pincode.proto.Access.Type\x12\x0b\n\x03tid\x18\x05 \x01(\x04\x12\x0b\n\x03wid\x18\x06 \x01(\x04\"7\n\x04Type\x12\n\n\x06UNKOWN\x10\x00\x12\x08\n\x04READ\x10\x01\x12\t\n\x05WRITE\x10\x02\x12\x0e\n\nREAD_WRITE\x10\x03\"H\n\x06Sample\x12%\n\x06\x61\x63\x63\x65ss\x18\x01 \x03(\x0b\x32\x15.pincode.proto.Access\x12\x17\n\x0fline_size_bytes\x18\x02 \x01(\r\"0\n\x07Profile\x12%\n\x06sample\x18\x01 \x03(\x0b\x32\x15.pincode.proto.Sample')



_ACCESS_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='pincode.proto.Access.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='UNKOWN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='READ', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WRITE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='READ_WRITE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=154,
  serialized_end=209,
)


_ACCESS = descriptor.Descriptor(
  name='Access',
  full_name='pincode.proto.Access',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='pc', full_name='pincode.proto.Access.pc', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='pincode.proto.Access.address', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time', full_name='pincode.proto.Access.time', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='pincode.proto.Access.type', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tid', full_name='pincode.proto.Access.tid', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='wid', full_name='pincode.proto.Access.wid', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACCESS_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=209,
)


_SAMPLE = descriptor.Descriptor(
  name='Sample',
  full_name='pincode.proto.Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='access', full_name='pincode.proto.Sample.access', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='line_size_bytes', full_name='pincode.proto.Sample.line_size_bytes', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=211,
  serialized_end=283,
)


_PROFILE = descriptor.Descriptor(
  name='Profile',
  full_name='pincode.proto.Profile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sample', full_name='pincode.proto.Profile.sample', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=285,
  serialized_end=333,
)

_ACCESS.fields_by_name['type'].enum_type = _ACCESS_TYPE
_ACCESS_TYPE.containing_type = _ACCESS;
_SAMPLE.fields_by_name['access'].message_type = _ACCESS
_PROFILE.fields_by_name['sample'].message_type = _SAMPLE
DESCRIPTOR.message_types_by_name['Access'] = _ACCESS
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
DESCRIPTOR.message_types_by_name['Profile'] = _PROFILE

class Access(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCESS
  
  # @@protoc_insertion_point(class_scope:pincode.proto.Access)

class Sample(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAMPLE
  
  # @@protoc_insertion_point(class_scope:pincode.proto.Sample)

class Profile(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROFILE
  
  # @@protoc_insertion_point(class_scope:pincode.proto.Profile)

# @@protoc_insertion_point(module_scope)
